### ISSUE TITLE
Will using this cause blocking business logic？

### ISSUE THREAD

**Issue by runtu666** [open-telemetry/opentelemetry-php-instrumentation#58]
Is this method reported synchronously or asynchronously? If my collection service is unavailable, will it affect my business?

**Comment by brettmc** [comment]
Auto-instrumentation `pre` and `post` hooks will run synchronously. If your question is more generally about exporting telemetry (traces, metrics, logs) then yes, it is almost always blocking because of how PHP works.
We usually recommend using one or more instances of the opentelemetry collector (eg as a sidecar, or located very close) so that you can offload telemetry quickly, and let the collector worry about forwarding on.

But, if your collector is unavailable or misconfigured, then yes requests will usually be delayed waiting for a connection timeout.

**Comment by runtu666** [comment]
Is there any demo about using OpenTelemetry PHP Auto-Instrumentation  [https://opentelemetry.io/blog/2023/php-auto-instrumentation/](url)

**Comment by brettmc** [comment]
The quote service in https://github.com/open-telemetry/opentelemetry-demo uses auto-instrumentation. It's a small slim framework app.

**Comment by runtu666** [comment]
@brettmc 
Can I save the tracing data first, such as saving it in a file, or saving it in a message queue or database, and then start another program to report these link tracking data to jeager？Is there a related demo for reference?

**Comment by brettmc** [comment]
@runtu666 Yes you could theoretically export signals to another data store, but there is not a way to send that data on to a backend from an arbitrary data source (to my knowledge).

You should use the opentelemetry collector [as an agent](https://opentelemetry.io/docs/collector/deployment/agent/). It can act as the data store, and batch up data to send to your backend.
re: your original question, it will still delay business logic if the collector was unavailable. But, when running as an agent it should be very fast and you can test out reducing your timeouts to quite small numbers.

Based on your questions, I did add some documentation about dealing with export delays: https://opentelemetry.io/docs/instrumentation/php/exporters/#minimizing-export-delays

**Comment by runtu666** [comment]
ok! got it! thank you! @brettmc
